import sys, os, time
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from PySide6.QtWidgets import QApplication
from PySide6.QtCore import QTimer
import traceback

print('starting test_playback')
app = QApplication([])
try:
    from player import VideoPlayer
    vp = VideoPlayer()
    vp.show()
    # find a test video generated by integration_test_split
    test_vid = os.path.join(ROOT, 'test_out', 'test_input.mp4')
    if not os.path.exists(test_vid):
        print('test video not found:', test_vid)
    else:
        print('found test video:', test_vid)
        vp.add_to_queue([test_vid], play_immediately=True)

    def check():
        try:
            pl = vp.player.playbackState()
            ms = vp.player.mediaStatus()
            err = None
            try:
                err = vp.player.error()
            except Exception:
                pass
            print('playbackState=', pl)
            print('mediaStatus=', ms)
            print('error=', err)
            # if possible print position and duration
            try:
                print('position=', vp.player.position(), 'duration=', vp.player.duration())
            except Exception:
                pass
        except Exception:
            traceback.print_exc()
        QTimer.singleShot(500, app.quit)

    QTimer.singleShot(1500, check)
    app.exec()
    print('app finished')
except Exception:
    traceback.print_exc()
    sys.exit(1)

